server:
  port: 8080
  servlet.context-path: /api

spring:
  profiles.active: dev
  application.name: ExamenTecso
      
---
#DEV CONFIGURATION
spring:
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tecsoexamendb?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

---        
#PROD CONFIGURATION
spring:
  profiles: qa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa